name: fit_ness_territory
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.17.0
  cupertino_icons: ^1.0.8
  dio: ^5.0.0
  flutter_polyline_points: ^2.0.0
  geolocator: ^14.0.2

  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"